version: '3.8'

services:
  backend:
    build: ./spreadsheet
    volumes:
      - ./spreadsheet:/app
    working_dir: /app
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: spreadsheet_development
      RAILS_ENV: development

  frontend:
    build: ./NATech
    volumes:
      - ./NATech:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: spreadsheet_development
    ports:
      - "5432:5432"

volumes:
  postgres_data:
